<?php

use AWSD\Template\Section;
use AWSD\Template\Partial;
?>
<!-- templates/layout.php -->
<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <title><?= Section::yield("title", "HomePage") ?></title>
</head>

<body>
  <?= Partial::render("header") ?>

  <main>
    <?= Section::yield("content") ?>
  </main>

  <footer>
    <p>&copy; <?= date('Y') ?> Mon site</p>
  </footer>
</body>

</html>